sections:
  - id: "ah_markets"
    name: "A股 / H股焦点"
    include:
      - "A股"
      - "沪指"
      - "深成指"
      - "创业板"
      - "科创"
      - "港股"
      - "恒生"
      - "恒指"
      - "H股"
      - "券商"
      - "北向"
      - "南向"
      - "AH股"
      - "成交"
      - "上证"
      - "中概"
    exclude:
      - "美股"
      - "纳指"
      - "道指"
      - "标普"
    max_items: 6
    exclusive: true
    min_items: 3
    fallback_keywords:
      - "股市"
      - "指数"
      - "行情"
      - "涨"
      - "跌"
      - "市场"

  - id: "domestic_politics"
    name: "国内热点 · 时政"
    include:
      - "国务院"
      - "中央"
      - "中共中央"
      - "国常会"
      - "发改委"
      - "工信部"
      - "财政部"
      - "两会"
      - "十四五"
      - "总书记"
      - "部委"
      - "新政"
      - "改革"
      - "政策"
      - "外交部"
      - "国内"
      - "央行"
      - "国资"
      - "金融监管"
      - "住建部"
    exclude:
      - "美股"
      - "港股"
    max_items: 6
    exclusive: true
    min_items: 3
    fallback_keywords:
      - "中国"
      - "政策"
      - "本土"
      - "国内"
      - "权威"

  - id: "global_politics"
    name: "海外热点 · 时政"
    include:
      - "美国"
      - "白宫"
      - "拜登"
      - "特朗普"
      - "欧盟"
      - "欧洲"
      - "英国"
      - "德国"
      - "法国"
      - "俄罗斯"
      - "乌克兰"
      - "以色列"
      - "巴以"
      - "中东"
      - "伊朗"
      - "朝鲜"
      - "日本"
      - "韩国"
      - "联合国"
      - "G7"
      - "G20"
      - "北约"
    exclude:
      - "A股"
      - "港股"
    max_items: 6
    exclusive: true
    min_items: 3
    fallback_keywords:
      - "海外"
      - "国际"
      - "全球"
      - "外媒"
      - "境外"
